kind: Pod
apiVersion: v1
metadata:
  name: test1
  namespace: default
  selfLink: /api/v1/namespaces/default/pods/test1
  uid: 7183ff01-cfd4-4a13-839a-144ecee69729
  resourceVersion: '32907'
  creationTimestamp: '2020-12-22T22:25:08Z'
  labels:
    run: test1
  managedFields:
    - manager: kubectl-run
      operation: Update
      apiVersion: v1
      time: '2020-12-22T22:25:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:run': {}
        'f:spec':
          'f:containers':
            'k:{"name":"test1"}':
              .: {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:ports':
                .: {}
                'k:{"containerPort":8080,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2020-12-22T22:25:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"172.17.0.5"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
spec:
  volumes:
    - name: default-token-7nqmt
      secret:
        secretName: default-token-7nqmt
        defaultMode: 420
  containers:
    - name: test1
      image: romanovns/kubernetesapp
      ports:
        - containerPort: 8080
          protocol: TCP
      resources: {}
      volumeMounts:
        - name: default-token-7nqmt
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: minikube
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-12-22T22:25:08Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-12-22T22:25:28Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-12-22T22:25:28Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-12-22T22:25:08Z'
  hostIP: 192.168.49.2
  podIP: 172.17.0.5
  podIPs:
    - ip: 172.17.0.5
  startTime: '2020-12-22T22:25:08Z'
  containerStatuses:
    - name: test1
      state:
        running:
          startedAt: '2020-12-22T22:25:27Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: 'romanovns/kubernetesapp:latest'
      imageID: >-
        docker-pullable://romanovns/kubernetesapp@sha256:2675cd9006f499143df74ee76906d45cd10223d22c5a8ee4f9cdaf8844ed6342
      containerID: >-
        docker://b07eefedd81c03fec9a91f00e36182c997463967c5638134cb73757ac6896d5e
      started: true
  qosClass: BestEffort
