version: "2.0"
services:
  web1:
    image: counterappredis
    container_name: counterapp_1
    ports:
      - "8081:8080"
    command: -serverid 1
  web2:
    image: counterappredis
    container_name: counterapp_2
    ports:
      - "8082:8080"
    command: -serverid 2
  web3:
    image: counterappredis
    container_name: counterapp_3
    ports:
      - "8083:8080"
    command: -serverid 3
  storage:
    image: redis
    container_name: myredis
    ports:
    - "8085:6379"
  balancer:
    image: lb_random
    container_name: balancer
    ports:
      - "8080:80"